# Включение питания на люстру
- alias: 02_toilet_autoswitch
  initial_state: false
  trigger:
  - platform: state
    entity_id: switch.wall_switch_left_158d00014dceb3
    to: 'off'
  action:
  - delay: 00:00:03
  - service: switch.turn_on
    entity_id:
      - switch.wall_switch_left_158d00014dceb3
      
# Перезагрузка зависшей люстры
- alias: 02_toilet_reboot
  initial_state: false
  trigger:
  - platform: state
    entity_id: light.yeelight_02_ceiling
    to: 'unavailable'
    for:
      minutes: 5
  action:
    - service: notify.telegram
      data:
        message: "Потеря контроля в течении 5 минут - люстра в туалете.  Время события - {{ states('sensor.time_date') }} . Инициирована перезагрузка"
    - service: switch.turn_off
      entity_id: switch.wall_switch_left_158d00014dceb3
      
## Возобновление питания на выключателе стиралки
- alias: 04_kn_power
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: state
      entity_id: switch.bw_relay
      state: 'off'
  action:
   - service: switch.turn_on
     entity_id: switch.bw_relay

# Автоматическая установка яркости
- alias: 02_toilet_light
  initial_state: false
  trigger:
  - platform: state
    entity_id: light.yeelight_02_ceiling
    to: 'on'
  action:
  - service: light.turn_on
    entity_id:
      - light.yeelight_02_ceiling
    data_template:
       brightness_pct: >
         {%- if states("binary_sensor.tod_night") == 'on' -%}
         25
         {%- elif states("binary_sensor.tod_day") == 'on'  -%}
         75
         {%- else -%}
         50
         {% endif %}
       kelvin: 4000
  - service: timer.cancel
    entity_id: timer.toilet
  - service: timer.start
    entity_id: 
      - timer.toilet
    data_template: 
        duration: > 
         {%- if states("binary_sensor.tod_long_day") == 'on' -%}
         00:10:00
         {%- else -%}
         00:05:00
         {% endif %}

## Таймер освещения обновление
- alias: 02_toilet_light_timer_reload
  initial_state: false
  trigger:
# Датчик движения
  - platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d0001a24e71
  condition:
    - condition: state
      entity_id: light.yeelight_02_ceiling
      state: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.toilet
  - service: timer.start
    entity_id: 
      - timer.toilet
    data_template: 
        duration: > 
         {%- if states("binary_sensor.tod_long_day") == 'on' -%}
         00:10:00
         {%- else -%}
         00:05:00
         {% endif %}

# Сброс таймера при выключении
- alias: 02_toilet_timer_off
  initial_state: false
  trigger:
  - platform: state
    entity_id: light.yeelight_02_ceiling
    to: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.toilet

# Включение освещения 
- alias: 02_toilet_light_on
  initial_state: false
  trigger:
# Таймер
  - platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id:  binary_sensor.motion_sensor_158d0001a24e71
# Выключатель в туалете
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d000128cd1a
      click_type: single  
  condition:
  - condition: state
    entity_id: light.yeelight_02_ceiling
    state: 'off'
  action:
  - service: light.turn_on
    entity_id:
      - light.yeelight_02_ceiling

# Выключение освещения       
- alias: 02_toilet_light_off
  initial_state: false
  trigger:
# Датчик движения
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.toilet
# Выключатель в туалете
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d000128cd1a
      click_type: single
  condition:
  - condition: state
    entity_id: light.yeelight_02_ceiling
    state: 'on'
  action:
  - service: light.turn_off
    entity_id:
      - light.yeelight_02_ceiling
 
# Выключение освещения с задержкой  
- alias: 02_toilet_light_off_delay
  initial_state: false
  trigger:
# Выключатель в туалете
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_both_158d000128cd1a
      click_type: both   
  condition:
  - condition: state
    entity_id: light.yeelight_02_ceiling
    state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.02_change_brightness
  - delay: 00:00:10
  - service: light.turn_off
    entity_id:
      - light.yeelight_02_ceiling

# Управление вентиляцией   
- alias: 02_toilet_vent
  initial_state: false
  trigger:
# Выключатель в туалете
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d000128cd1a
      click_type: single   
  action:
  - service: switch.toggle
    entity_id: switch.wall_switch_right_158d00014dceb3

# Включение таймера
- alias: 02_toilet_vent_timer
  initial_state: false
  trigger:       
   platform: state
   entity_id: switch.wall_switch_right_158d00014dceb3
   to: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.toilet_v
  - service: timer.start
    entity_id: timer.toilet_v
    
# Выключение таймера
- alias: 02_toilet_vent_timer_off
  initial_state: false
  trigger:       
   platform: state
   entity_id: switch.wall_switch_right_158d00014dceb3
   to: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.toilet_v

# Выключение вентиляциии
- alias: 02_toilet_vent_off
  initial_state: false
  trigger:       
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.toilet_v
  action:
  - service: switch.turn_off
    entity_id: switch.wall_switch_right_158d00014dceb3

# Включение света на 15 секунд по движению
- alias: 02_prachec_motion
  initial_state: false
  trigger:
# Датчик движения
   platform: event
   event_type: xiaomi_aqara.motion
   event_data:
     entity_id: binary_sensor.motion_sensor_158d0001e16204
  condition:
  - condition: state
    entity_id: light.aqara_02_ceiling
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.aqara_02_ceiling
  - delay: 00:00:15
  - service: light.turn_off
    entity_id: light.aqara_02_ceiling
    
## Обнаружение протечки, стиралка 
- alias: 02_prachec_wleak_washmash_on
  initial_state: false
  trigger:       
   platform: state
   entity_id: binary_sensor.water_leak_sensor_158d0002705b7b
   to: 'on'
  action:
  - service: notify.telegram
    data:
      title: "Обнаружена протечка"
      message: "Стиральная машина {{ states('sensor.time_date') }}"
  - service: script.turn_on
    entity_id: script.11_warning
      
## Протечка устранена, стиралка        
- alias: 02_prachec_wleak_washmash_off
  initial_state: false
  trigger:       
   platform: state
   entity_id: binary_sensor.water_leak_sensor_158d0002705b7b
   from: 'on'
   to: 'off'
  action:
  - service: notify.telegram
    data:
      title: "Протечка устранена"
      message: "Стиральная машина {{ states('sensor.time_date') }}"
  - service: script.turn_on
    entity_id: script.11_all_ok
    
## Запись последнего движения в туалете
- alias: 02_toilet_motion_time
  initial_state: true
  trigger:
## Движение в туалете
  - platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d0001a24e71
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d0001a24e71"
      payload: "{{ states('sensor.time_date')}}"
      retain: true
      
## Запись последнего движения в прачечной
- alias: 02_prachec_motion_time
  initial_state: true
  trigger:
## Движение в прачечной
  - platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d0001e16204
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d0001e16204"
      payload: "{{ states('sensor.time_date')}}"
      retain: true