## Возобновление питания на выключателе холодильника
- alias: 04_kn_power
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: state
      entity_id: switch.plug_158d0001fa2934
      state: 'off'
  action:
   - service: switch.turn_on
     entity_id: switch.plug_158d0001fa2934
     
## Включение люстры
- alias: 04_kn_ceiling
  initial_state: false
  trigger:
## Выключатель на входе в кухню - правая кнопка
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d000282a130
      click_type: single
## Круглая кнопка на стене
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000154a353
      click_type: long_click_press
## Подброс кубика
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000101bdc6
      action_type: free_fall      
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
         {%- if states.light.philips_04_ceiling.state == 'off'-%}
         script.04_kn_ceiling_on
         {%- elif states.light.philips_04_ceiling.state == 'on' and states("sensor.philips_04_ceiling") | int <= 1  -%}
         script.04_kn_ceiling_off
         {%- elif states.light.philips_04_ceiling.state == 'on' and states("sensor.philips_04_ceiling") | int >= 2  -%}
         script.04_kn_ceiling_on
         {% endif %}  
         
# Автоматическое включение люстры
- alias: 04_kn_ceiling_auto_on
  initial_state: false
  trigger:
# Датчик движения
  - platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d0001ab3350
  condition:
# Условие И - лампа выключена
   condition: and
   conditions:
    - condition: state
      entity_id: light.philips_04_ceiling
      state: 'off'
# Второе условие И - одно из двух
    - condition: or
      conditions:
# Освещенность ниже 800 с шлюза
         - condition: numeric_state
           entity_id: sensor.illumination_7811dc64f4c8
           below: 800
# Время между закатом и рассветом
         - condition: state
           entity_id: binary_sensor.tod_full_night
           state: 'on'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-        
         {%- if states("binary_sensor.tod_night") == 'on' -%}
         script.04_kn_ceiling_auto_4
         {%- elif states("binary_sensor.tod_day") == 'on'  -%}
         script.04_kn_ceiling_auto_2
         {%- else -%}
         script.04_kn_ceiling_auto_3
         {% endif %}
         
# Автоматическое выключение люстры 
- alias: 04_kn_ceiling_auto_off
  initial_state: false
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d0001ab3350
    from: 'on'
    to: 'off' 
  condition:
   - condition: state
     entity_id: light.philips_04_ceiling
     state: 'on'
   - condition: numeric_state
     entity_id: sensor.philips_04_ceiling
     above: 1
  action:
    - service: script.turn_on
      entity_id: script.04_kn_ceiling_off

# Включение подсветки  
- alias: 04_kn_led_toggle
  initial_state: false
  trigger:
## Круглая кнопка на стене
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000154a353
      click_type: single
  - platform: event
## Переворот кубика на 90 градусов
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000101bdc6
      action_type: flip90
## Выключатель на входе в кухню - левая кнопка
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d000282a130
      click_type: single
  action:
    service: light.toggle
    entity_id: light.aqara_04_strip

## Обнаружение протечки, раковина     
- alias: 04_kitchen_wleak_washstand_on
  initial_state: false
  trigger:       
   platform: state
   entity_id: binary_sensor.water_leak_sensor_158d0001bbeba6
   to: 'on'
  action:
  - service: notify.telegram
    data:
      title: "Обнаружена протечка"
      message: "Кухня раковина {{ states('sensor.time_date') }}"
  - service: script.turn_on
    entity_id: script.11_warning


## Протечка устранена, раковина          
- alias: 04_kitchen_wleak_washstand_off
  initial_state: false
  trigger:       
   platform: state
   entity_id: binary_sensor.water_leak_sensor_158d0001bbeba6
   from: 'on'
   to: 'off'
  action:
  - service: notify.telegram
    data:
      title: "Протечка устранена"
      message: "Кухня раковина {{ states('sensor.time_date') }}"
  - service: script.turn_on
    entity_id: script.11_all_ok

## Управление телевизором       
- alias: 04_tv_xiaomi
  initial_state: false
  trigger:
## Круглая кнопка на стене 
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000154a353
      click_type: double 
## Правая клавиша, выключатель на входе   
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d000282a130
      click_type: double
## Двойной тап кубиком
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000101bdc6
      action_type: tap_twice
  action:
    service: script.turn_on
    entity_id: script.xiaomi_tv

## Датчик вибрации     
- alias: 04_photo_on_vibro
  initial_state: false
  trigger:
## Датчик вибрации
  - platform: event
    event_type: xiaomi_aqara.movement
    event_data:
      entity_id: binary_sensor.vibration_158d0002a8ab8b
      click_type: vibrate
  action:
  - service: script.turn_on
    entity_id: script.04_photo_reolink2
    
## Запись последнего движения в кухне
- alias: 04_kitchen_motion_time
  initial_state: true
  trigger:
## Движение в кухне
  - platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d0001ab3350
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d0001ab3350"
      payload: "{{ states('sensor.time_date')}}"
      retain: true
