## Включение по движению
- alias: 08_da_light_auto
  initial_state: false
  trigger:
## Датчик движения
  - platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id:  binary_sensor.motion_sensor_158d00016d56f5  
  condition:
   condition: and
   conditions:
## Выключена люстра
   - condition: state
     entity_id: light.aqara_08_ceiling
     state: 'off'
## Выключен прикроватник
   - condition: state
     entity_id: light.yeelight_08_bedside
     state: 'off'
## Вечером    
   - condition: or
     conditions:
       - condition: sun
         after: sunset
       - condition: sun
         before: sunrise
  action:
  - service: light.turn_on
    entity_id: 
     - light.gateway_light_f0b429cc1f11
    data_template:
       brightness_pct: 50
       rgb_color: [0, 0, 255]
  - delay: 00:00:15
  - service: light.turn_off
    entity_id: 
     - light.gateway_light_f0b429cc1f11

## Управление освещением
- alias: 08_da_light
  initial_state: false
  trigger:
## Выключатель на входе
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_158d00010b5c6e
      click_type: single
## Круглая кнопка возле кровати
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000155d2fb
      click_type: single
## Круглая кнопка на столе
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000186d9a9
      click_type: single
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
         {%- if states.light.aqara_08_ceiling.state == 'off' and states.light.yeelight_08_bedside.state == 'off' and states("binary_sensor.tod_long_day") == 'on' -%}
         script.08_da_ceiling_on
         {%- elif states.light.aqara_08_ceiling.state == 'off' and states.light.yeelight_08_bedside.state == 'off' and states("binary_sensor.tod_early_night") == 'on' -%}
         script.08_da_nightlight
         {%- elif states.light.aqara_08_ceiling.state == 'off' and states.light.yeelight_08_bedside.state == 'on' -%}
         script.08_da_nightlight_off
         {%- elif states.light.aqara_08_ceiling.state == 'on' and states.light.yeelight_08_bedside.state == 'on' -%}
         script.08_da_nightlight_off
         {%- elif states.light.aqara_08_ceiling.state == 'on' and states.light.yeelight_08_bedside.state == 'off' -%}
         script.08_da_ceiling_off
         {% endif %}       

## Управление циклической подсветкой
- alias: 08_da_light_circle
  initial_state: false
  trigger:
## Круглая кнопка возле кровати
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000155d2fb
      click_type: double
## Круглая кнопка на столе
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000186d9a9
      click_type: double
## Кубик
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028f6fe6
      action_type: shake_air
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
         {%- if states.light.yeelight_08_bedside.state == 'off' -%}
         script.08_da_light_circle_1
         {%- elif states.light.yeelight_08_bedside.state == 'on' -%}
         script.08_da_nightlight_off
         {% endif %}  


# Выключение всего освещения
- alias: 08_da_alllight_off
  initial_state: false
  trigger:
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028f6fe6
      action_type: free_fall      
  action:
    - service: script.turn_on
      entity_id: script.08_da_lightoff
      
# Перезагрузка настольной лампы     
- alias: 08_da_table_reboot
  initial_state: false
  trigger:
   platform: state
   entity_id: light.yeelight_08_table
   to: 'unavailable'
   for:
     minutes: 5
  action:
#    - service: notify.telegram
#      data:
#        message: "Потеря контроля в течении 5 минут - Настольная лампа, ДА.  Время события - {{ states('sensor.time_date') }} . Инициирована перезагрузка"
    - service: switch.turn_off
      entity_id: switch.alfawise_relay
    - delay: 00:00:05
    - service: switch.turn_on
      entity_id: switch.alfawise_relay


## Запись последнего движения в детской А
- alias: 08_da_motion_time
  initial_state: true
  trigger:
## Движение в детской А
  - platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d00016d56f5
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d00016d56f5"
      payload: "{{ states('sensor.time_date')}}"
      retain: true