- platform: systemmonitor
  resources:
  - type: processor_use
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: last_boot
  - type: disk_free
    arg: /
    
- platform: filesize
  file_paths:
     - /config/home-assistant_v2.db
     
- platform: sql
  db_url: !secret db_link
  queries:
    - name: Maria DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB
    
- platform: command_line
  name: cpu_temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'
  
- platform: rest
  resource: http://192.168.0.70:8123/api/states/sensor.online_custom?api_password=qwerty
  name: main_state
  force_update: true
  value_template: '{{ value_json.state }}'
  
#- platform: rest
#  resource: http://192.168.0.71:8123/api/states/sensor.online_custom?api_password=qwerty
#  name: orange2_state
#  force_update: true
#  value_template: '{{ value_json.state }}'